feat(/api/0.6/changeset/#id/close): new route
MapColonies/node-osm-api pull request #12
Opened 2020-11-30 08:44 UTC by galta95

2020-11-30 18:49 UTC, syncush requested changes

2020-12-03 07:50 UTC, galta95 commented on README.md
>  easy communication with osm api
I will do it at the end

2020-12-03 07:50 UTC, galta95 commented on src/api/v6/index.ts
> +} from '../../lib/error-handler';
done

2020-12-03 07:50 UTC, galta95 commented on src/api/v6/index.ts
> +          axiosError.response.data === "The user doesn't own that changeset"
1. works, but when there is single quote inside the string it converts to double quote
2. done 
3. done

2020-12-03 07:54 UTC, syncush approved these changes

2020-12-03 08:33 UTC, merged